//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteArchi3D
{
    using System;
    using System.Collections.Generic;
    
    public partial class Modélisateurs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Modélisateurs()
        {
            this.Liste_de_Prestataires = new HashSet<Liste_de_Prestataires>();
        }
    
        public int idModélisateur { get; set; }
        public int xid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Liste_de_Prestataires> Liste_de_Prestataires { get; set; }
        public virtual Personnes Personnes { get; set; }
    }
}
