//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteArchi3D
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Projet()
        {
            this.Archives = new HashSet<Archives>();
            this.Création_de_Projet = new HashSet<Création_de_Projet>();
        }
    
        public int idProjet { get; set; }
        public string Promoteur { get; set; }
        public System.DateTime Date_début { get; set; }
        public System.DateTime Date_fin { get; set; }
        public decimal Avancement { get; set; }
        public int Liste_prestataires { get; set; }
        public int xidCommentaires { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Archives> Archives { get; set; }
        public virtual Commentaires Commentaires { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Création_de_Projet> Création_de_Projet { get; set; }
        public virtual Liste_de_Prestataires Liste_de_Prestataires { get; set; }
    }
}
