//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteArchi3D
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promoteur
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Promoteur()
        {
            this.Création_de_Projet = new HashSet<Création_de_Projet>();
        }
    
        public int idPromoteur { get; set; }
        public int xid { get; set; }
        public bool admin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Création_de_Projet> Création_de_Projet { get; set; }
        public virtual Account Account { get; set; }
    }
}
