//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteArchi3D
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjetSiteArchi3DEntities : DbContext
    {
        public ProjetSiteArchi3DEntities()
            : base("name=ProjetSiteArchi3DEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Architecte> Architecte { get; set; }
        public virtual DbSet<Archives> Archives { get; set; }
        public virtual DbSet<Commentaires> Commentaires { get; set; }
        public virtual DbSet<Liste_de_Prestataires> Liste_de_Prestataires { get; set; }
        public virtual DbSet<Modélisateurs> Modélisateurs { get; set; }
        public virtual DbSet<Personnes> Personnes { get; set; }
        public virtual DbSet<Promoteur> Promoteur { get; set; }
        public virtual DbSet<Qualité> Qualité { get; set; }
        public virtual DbSet<QuestionnaireProjet> QuestionnaireProjet { get; set; }
        public virtual DbSet<Signup> Signup { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Création_de_Projet> Création_de_Projet { get; set; }
        public virtual DbSet<Projet> Projet { get; set; }
    }
}
