//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteArchi3D.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Archives
    {
        public int id { get; set; }
        public int xidProjetFini { get; set; }
        public byte[] Fichiers { get; set; }
        public byte[] Images { get; set; }
        public string ListePrestatairesProjet { get; set; }
    
        public virtual Projet Projet { get; set; }
    }
}
